name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run linting
        run: npm run lint
      
      - name: Run tests
        run: npm test
  
  build:
    name: Build and Push Docker image
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/hashi:latest
            ghcr.io/${{ github.repository }}/hashi:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64
          
      - name: Verify ChimeraX in the Docker image
        run: |
          docker pull ghcr.io/${{ github.repository }}/hashi:${{ github.sha }}
          docker create --name test-container ghcr.io/${{ github.repository }}/hashi:${{ github.sha }}
          docker cp test-container:/usr/bin/chimerax /tmp/chimerax || echo "ChimeraX not found at expected path"
          docker rm test-container

  deploy-staging:
    name: Deploy to Staging
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Deploy to staging environment
        run: echo "Deploying to staging environment..."
        # Add deployment commands here
        
      - name: Run smoke tests
        run: echo "Running smoke tests..."
        # Add smoke test commands here

  validate-environments:
    name: Validate Environments
    runs-on: ubuntu-latest
    needs: test
    
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Verify dependencies
        run: |
          chmod +x scripts/verify-dependencies.sh
          bash scripts/verify-dependencies.sh || echo "Some dependencies may not be available on GitHub Actions"